cloudbuild.yaml
I copied this straight out of craft
=> build: Add cloudbuilder configuration

.craft.yml, .dockerignore, Dockerfile, cloudbuild.yaml
- Switch to 2-step build process for Docker images, reducing build times and final runtime image size
- Add `:latest` image publishing to Craft
=> ci(docker): Overhaul Docker stuff

yarn.lock
Run `volta run yarn-deduplicate --strategy fewer yarn.lock; yarn` commit
=> ref(yarn): Slim down yarn.lock and deps

Dockerfile
This is basically just for documentation purposes
=> build: Expose port 9090 in dockerfile

src/renderServer.ts
=> ref: Bump the json parsing size limit

src/config.ts, src/configPolling.ts, src/types.ts
=> fix(boot): Correct fetchConfig timeout

cloudbuild.yaml
bringing this more in line with other cloudbuild files and trying to fix
the freight cloudbuild test
=> cloudbuild changes s/nightly/latest/g

cloudbuild.yaml
should fix this stuff: https://console.cloud.google.com/cloud-build/builds/54ca4997-104b-4935-8c86-39efc7c57c64;step=3?project=sentryio
=> again, need to use the correct name

.github/workflows/build.yml, Dockerfile, package.json, yarn.lock
Let's keep things in line with everything else
=> chore(js): Bump to node 16 LTS

src/renderServer.ts
Attempting to send less data to sentry without changing the tracesSampleRate. Right now the health routes tpm is 1375
Also disables the http monitor
=> feat: ignore healthcheck routes in sentry

src/renderServer.ts
Enable performance tracing (precursor to enabling profiling)
=> feat(sentry): add performance tracing

package.json, src/renderServer.ts, yarn.lock
Enable profiling feature for chartcuterie (example when DSN is set https://sentry.io/organizations/sentry/profiling/profile/chartcuterie/2c23822cf46a4425a587004eefa85f4e/flamechart/?colorCoding=by+symbol+name&fov=0%2C46%2C101833000%2C9&query=&sorting=call+order&tid=0&view=top+down&xAxis=standalone)
=> feat(sentry): enable profiling

src/render.ts
This reverts commit 02fe910e516812242ef414305c6d4488285ba2fa.
=> Revert "perf(echarts): pass options to init directly (#99)"

package.json, yarn.lock
bump to 0.0.6 which adds spans for start/stop so we can see where the delays are coming from
=> deps(profiling): bump 0.0.6

package.json, yarn.lock
Fixed quite a few bugs from 0.0.6 to 0.0.12, this should now be stable for alpha
=> deps(sentry): bump packages

README.md
Add some instructions for running locally on macOS.
=> chore(docs): Clarify local dependencies

gocd/pipelines/chartcuterie.yaml
=> gocd: need github_token

gocd/pipelines/chartcuterie.yaml
Committed via https://github.com/asottile/all-repos
=> Update to new k8s deploy script

gocd/pipelines/chartcuterie.yaml
=> cd: auto canary and simplify

package.json, src/renderServer.ts, yarn.lock
See: https://github.com/getsentry/sentry-javascript/discussions/9973
=> ref: Add Sentry metrics to Chartcuterie

package.json, src/index.ts, src/renderServer.ts, yarn.lock
Sentry master acceptance tests are failing.
=> fix: Revert SDK bump

.craft.yml, gocd/pipelines/chartcuterie.yaml
=> ref: deploy from artifact registry

src/config.ts
=> ref(node): Inject URL and URLSearchParams globals

gocd/templates/bash/check-cloudbuild.sh, gocd/templates/bash/check-github-runs.sh
These scripts only accept positional args.
=> fix(gocd): Switching back to positional args

package.json, src/instrument.ts, yarn.lock
Fixes the type issue and chunk timestamp
=> deps(sentry) bump to 8.11

gocd/templates/chartcuterie.jsonnet, gocd/templates/pipelines/chartcuterie.libsonnet
Adding S4S deploy, updating canary to only run for US and DE.
=> chore(gocd): adding s4s deploy

gocd/templates/jsonnetfile.json, gocd/templates/jsonnetfile.lock.json
=> change: Update gocd jsonlib to 2.13
