getsentry/chartcuterie

src/index.ts
src/logging.ts

When rendering via std{in,out} we have to be careful not to write out anythings else to stdout.

Output console logging to stderr for `render`

---

.craft.yml

This is why we don't see the releases on GitHub releases page and changlog links have `null` in them.

ci(release): Publish to GitHub releases too

---

cloudbuild.yaml

It wasn't actually tagging the nightly build

build: Add missing tagging for nightly

---

package.json
src/config.ts
src/configPolling.ts
src/index.ts
src/renderServer.ts
src/types.ts
tests/config.spec.ts
tests/configPolling.spec.ts
tests/renderServer.spec.ts
tests/renderStream.spec.ts
tests/validate.spec.ts
yarn.lock

Adds a `--configPolling flag to the server command, that will poll for config resolution. This allows the configuration be updated by publishing a new valid configuration module to the well known URL the service is configured for.
Polling during boot before it initally has a config happens every 5 seconds. Once booted it will poll for a new config file ever 5 minutes.

feat: Add config polling

---

src/renderServer.ts
tests/renderServer.spec.ts

This is to match `relay` : 
https://github.com/getsentry/single-tenant/blob/master/k8s/relay/deployment.yaml#L66-L74
sorry for the extra work. Should have caught this before the last PR

new health check live and ready endpoints

---

src/config.ts

In webpack4 the module we were building had a different output structure I think..

fix(http-config): Pull default from module exports

---

package.json
src/index.ts
src/renderServer.ts
yarn.lock

Initialize sentry right after express app is initialized, add tracing handler
Related [PR](https://github.com/getsentry/sentry/pull/28114)

chore: Add sentry tracing package 

---

src/configPolling.ts

Log invalid config errors.
World map chart unfurls don't work, because
[chartcuterie isn't picking up world map type](https://sentry.io/organizations/sentry/discover/sentry:c0a282fec19847189a4f305105b90dc1/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=1&query=&sort=-timestamp&statsPeriod=1h&yAxis=count%28%29). Tracked
down some GCP logs, seeing the following:
`[33mwarn [39m: Resolved NEW but INVALID config. Not updating...`
Not able to replicate this locally either. To replicate
locally, enabled polling with `--configPolling=true`
when starting up the service, reduced the default polling
time and added a `delete require.cache[path.resolve(this.#uri)];`
in fetchConfig so it would read any new updates to the file.
Started without the …

debug: Log invalid config errors

---

package.json
yarn.lock

This small PR bumps the JS SDKs to version 7.0.0 stable following our major release

chore: Bump JS SDK to 7.0.0 stable

---

src/render.ts
src/renderServer.ts
src/renderStream.ts

Sometimes charts have invalid data passed to the chart options function. A 500 is expected, however each request is using more memory. Either from echarts.init being called and not disposed or it was erroring creating the echarts options which was after echarts.init, also causing dispose to not be called.

feat: Avoid calling echarts.init with invalid data object & always dispose

---

src/render.ts

We can pass options directly to the chart.init which will avoid calling updates to all of the components and redrawing the chart

perf(echarts): pass options to init directly

---

.github/workflows/image.yml

Thought the rename was innocent, but I missed a dependency.

Fix names for image jobs

---

.github/workflows/image.yml

Arm64 is slow to build on GitHub actions so we only have one image to set as latest vs a manifest.

Remove multiarch image

---

package.json
yarn.lock

Matches https://github.com/getsentry/sentry/pull/41042

chore(deps): bump echarts from 5.3.3 to 5.4.0

---

.github/workflows/lint-pipelines.sh
.github/workflows/lint-pipelines.yml
gocd/pipelines/chartcuterie.yaml

This adds deployment configurations for GoCD, the new internal continuous deployment tool. Please refer to the [Freight Migration Guide](https://www.notion.so/sentry/Freight-Migration-Guide-2bd47bb683254077ad31e7ad625345ae) for info on how to coordinate GoCD deploys during this transitional phase.
@asottile-sentry and I are planning on using this to test out canary deploys for chartcuterie (https://github.com/getsentry/ops/pull/5787) as a PoC for getsentry canary.

cd: add GoCD deployment pipeline

---

src/configPolling.ts

Trying to debug issues with the chartcuterie service in the hybrid cloud world.

chore: Capture config rendering errors as a Sentry error event

---

Dockerfile
cloudbuild.yaml
package.json
src/render.ts
yarn.lock

Chartcuterie runs on node 16, but sentry builds it with node 20 target which causes wrong core-js polyfills to be applied, which ends up throwing a runtime error.

deps: bump to node 20 to match sentry

---

src/index.ts
src/renderServer.ts

Sentry.init() needs to come before all the relevant imports

fix(instrumentation): Call `Sentry.init()` as early as possible

---

package.json
yarn.lock

This should fix an issue with undici
```
TypeError: request.headers.split is not a function
at setHeadersOnRequest (/usr/src/app/node_modules/@sentry/node/cjs/integrations/undici/index.js:248:39)
at _onRequestCreate (/usr/src/app/node_modules/@sentry/node/cjs/integrations/undici/index.js:158:9)
at Channel.publish (node:diagnostics_channel:143:9)
at new Request (node:internal/deps/undici/undici:6295:27)
at [dispatch] (node:internal/deps/undici/undici:9077:25)
at Intercept (node:internal/deps/undici/undici:8812:20)
at [Intercepted Dispatch] (node:internal/deps/undici/undici:5673:16)
at Client.dispatch (node:internal/deps/undici/undici:5689:44)
at [dispatch] (node:internal/deps/undici/undici:5920:32)
at [Intercepted Dispatch] (node:internal/deps/undici/undici:5666:33)
```
See …

chore(deps): Bump sentry

---

gocd/templates/pipelines/chartcuterie.libsonnet

We forgot the elastic_profile_id originally which caused GoCD to use a static agent which didn't have the necessary scripts available, causing the failures we saw.

fix(gocd): Adding elastic_profile_id

---

package.json
yarn.lock

Bump sentry libraries to the latest version so we can establish a baseline before bumping the version with contextlines change

deps: bump sentry to 8.9

---

src/instrument.ts

We want to start ingesting some profiles from a production env using the new continuous profiler

feat(profiling) use continuous profiler instead of the span/txn based one

---

gocd/templates/chartcuterie.jsonnet

Enable `chartcuterie` deployment where it is needed.

Enable chartcuterie deploy where it is needed

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/validate-pipelines.yml

Out of date GHA dependencies slowed down incident response. Keeping them updated in pinned should help us prevent that from happening in the future.

chore(ci): Updating and pinning all github actions used

---

src/config.ts
tests/config.spec.ts

This makes config file loading consistent between using the http config resolver and passing a local file path to load the config.
Consistency is important here for us since in Sentry we have chartucterie acceptance tests, which are there to help us catch changes made to Sentry's javascript app that may break chartucterie. However they are run with chartucterie having loaded the config using a file path and not HTTP, which differs from happens in production, where we resolve the config via HTTP and execute it in a vm context.
By making these consistent we catch errors that happen loading the config in the vm contextchartucterie VM.

ref: Use the VM to execute local config files

---

gocd/templates/bash/check-cloudbuild.sh

Cutting over to the new check_cloudbuild script that doesn't rely on images anymore and instead relies on repo_name, trigger_name, sha, and branch_name.
https://linear.app/getsentry/issue/DI-631/update-getsentrychartcuterie-to-use-new-script

ref(gocd): Cutting over to check_cloudbuild.py

---

gocd/templates/bash/check-cloudbuild.sh
gocd/templates/bash/check-github-runs.sh
gocd/templates/bash/deploy.sh

Updating gocd scripts to use console script entry points.
Please see: https://github.com/getsentry/devinfra-deployment-service/pull/698

ref(gocd): use console script entry points
